/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tennis.kata.accelerate

class App {
    val player1 = Player()
    val player2 = Player()

    // Ask for a better way to write parameter (enum?)
    fun getScore(ofPlayer1: Boolean): String {
        val player = if (ofPlayer1) player1 else player2
        val otherPlayer = if (ofPlayer1) player2 else player1

        var translatedScore: String = "love"

        when (player.score) {
            1 -> translatedScore = "15"
            2 -> translatedScore = "30"
            3 -> translatedScore = if (player1.score != player2.score) "40" else "deuce"
            else -> {
                if (
                    player1.score >= 3 &&
                    player2.score >= 3 &&
                    player.score - otherPlayer.score == 1
                ) {
                    translatedScore = "advantage"
                }
            }
        }

        return translatedScore
    }
}

fun main() {
    val app = App()
}
