/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tennis.kata.accelerate

class App {
    val player1 = Player()
    val player2 = Player()

    // Ask for a better way to write parameter (enum?)
    fun getScore(ofPlayer1: Boolean): String {
        val player = if (ofPlayer1) player1 else player2
        val otherPlayer = if (ofPlayer1) player2 else player1

        var translatedScore: String = "love"

        when (player.score) {
            0 -> translatedScore = "love"
            1 -> translatedScore = "15"
            2 -> translatedScore = "30"
            else -> {
                translatedScore = if (player.score >= 3 && otherPlayer.score >= 3) {
                    if (player.score == otherPlayer.score) {
                        "deuce"
                    } else if (player.score - otherPlayer.score == 1) {
                        "advantage"
                    } else if (player.score - otherPlayer.score == 2) {
                        "game"
                    } else "40"
                } else {
                    if (player.score - otherPlayer.score == 2) "game" else "40"
                }
            }
        }

        return translatedScore
    }
}

fun main() {
    val app = App()
}
