/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package tennis.kata.accelerate

import org.assertj.core.api.Assertions
import org.junit.jupiter.api.Test

class PlayerTest {

    @Test
    fun initialScoreForBothPlayersIs0() {
        val classUnderTest = Player()
        Assertions.assertThat(classUnderTest.score).isEqualTo(0)
    }

    @Test
    fun scoreIsIncreasedByOne() {
        val classUnderTest = Player()

        // Ask for a better way to do it
        for (i in 0..5) {
            val previousScore = classUnderTest.score
            classUnderTest.increaseScore()
            Assertions.assertThat(classUnderTest.score).isEqualTo(previousScore + 1)
        }
    }
}
